config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "city_quarters#show"
  resources :rounds, only: :update
  resources :city_quarters, only: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city_quarter.rb
class CityQuarter < ApplicationRecord
  has_many :users
  has_many :games, through: :users
  has_many :rounds
  
end

app/models/exercice.rb
class Exercice < ApplicationRecord
  has_many :rounds
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :round

  validates :user, presence: true
  validates :round, presence: true
  validates :finished_at, presence: true
  validates :user_id, uniqueness: {scope: :round_id}
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :exercice
  belongs_to :city_quarter
  has_many :games
  has_many :users, through: :games

  enum role: [ :student, :teacher ]
  enum progress: [ :pending, :active, :pasted ]

  validates :role, presence: true
  validates :rank, presence: true

  def unqualified_users
    city_quarter.users.where.not(id: users.map(&:id)).where(role: role)
  end

  def create_last_games(attrs={})
    unqualified_users.each do |user|
      begin
        url = "https://www.codewars.com/api/v1/users/#{user.cw_nickname}/code-challenges/completed"
        kata = JSON.parse(RestClient.get(url).body)["data"].find{|kata| kata["id"] == self.exercice.url}
        if kata && DateTime.parse(kata["completedAt"]).to_date == DateTime.now.to_date
          user.games.create(
            round: self,
            finished_at: DateTime.parse(kata["completedAt"]),
            rating: 10
          )
        elsif attrs[:finish]
          user.games.create(
            round: self,
            finished_at: DateTime.now,
            rating: 0
          )
        end
      rescue
      end
    end
    games.where
         .not(games: {rating: 0})
         .order(:finished_at)
         .each_with_index do |game, index|
            game.update(rating: (10 - index > 0) ? (10 - index) : 0)
          end
  end

  def can_be_revealed?
    pending? && (rank == 1 || city_quarter.rounds.where(role: role).find_by(rank: rank - 1, progress: :pasted))
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :city_quarter
  has_many :games

  enum role: [ :student, :teacher ]
  enum language: [ :ruby, :python, :sql ]

  validates :cw_nickname, presence: true
  validates :cw_nickname, uniqueness: { scope: :city_quarter,
    message: "The username codewars is already registered for this tournament" }

  validates :role, presence: true
  validates :language, presence: true

  validate :cw_nickname_exist
  validate :cw_nickname_is_new

  def cw_nickname_exist
    code = 100
    begin
      code = RestClient.get("https://www.codewars.com/api/v1/users/#{cw_nickname}").code
    rescue
      code = 404
    end
    if code != 200
      errors.add(:cw_nickname, "does not exist")
    end
  end

  def cw_nickname_is_new
    begin
      url = "https://www.codewars.com/api/v1/users/#{cw_nickname}/code-challenges/completed"
      kata_nbr = JSON.parse(RestClient.get(url).body)["data"].count
      errors.add(:cw_nickname, "is not newly initialized") if kata_nbr != 0
    rescue
      errors.add(:cw_nickname, "An error has occurred")
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    user_data = [
      :role,
      :language,
      :city_quarter,
      :city_quarter_id,
      :cw_nickname
    ]
    devise_parameter_sanitizer.permit(:sign_up, keys: user_data)
    devise_parameter_sanitizer.permit(:account_update, keys: user_data)
  end

  def current_city_quarter
    current_user.city_quarter
  end

end

app/controllers/city_quarters_controller.rb
class CityQuartersController < ApplicationController
  def show
    if current_user.admin
      student_active_round = current_city_quarter.rounds.find_by(progress: :active, role: :student )
      student_active_round&.create_last_games
      teacher_active_round = current_city_quarter.rounds.find_by(progress: :active, role: :teacher )
      teacher_active_round&.create_last_games
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def update
    @round = Round.find(params[:id])
    if @round.active?
      @round.create_last_games(finish: true)
      @round.pasted!
    elsif @round.pending?
      @round.active!
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_city_quarter
        current_user.city_quarter
    end
end

app/views/city_quarters/_results.html.erb
<div class="col-md-2 border-red py-3">
  <h3 class= "text-center">Results</h3>

  <% current_city_quarter.games.includes(:user).where(user: {role: role}).group(:user).sum(:rating).sort_by{|k, v| v}.reverse.each_with_index do |user_rating, index| %>
    <div class="card win-color win-<%= index + 1 %> w-100 p-3 my-3">
        <small class="size-18px"><%= index + 1 %> : <%= user_rating[0].cw_nickname %></small>

        <div class="d-flex w-100 justify-content-between">
          <small><%= user_rating[0].language %></small>
          <small><%= user_rating[-1] %>pts</small>
        </div>
    </div>
  <% end %>
</div>

app/views/city_quarters/show.html.erb
<div class="container">
  <h1 class="text-center my-5">Let's go <%= current_city_quarter.title %></h1>
  
  <hr>
  <h2 class="text-center my-5">Students (<%= current_city_quarter.users.where(role: :student).count %> pers)</h2>
  <div class="row">
    <%= render current_city_quarter.rounds.where(role: :student).order(:rank) %>
    <%= render "city_quarters/results", role: :student %>
  </div>

  <hr>
  <h2 class="text-center mt-4">Teachers (<%= current_city_quarter.users.where(role: :teacher).count %> pers)</h2>
  <div class="row">
    <%= render current_city_quarter.rounds.where(role: :teacher).order(:rank) %>
    <%= render "city_quarters/results", role: :teacher %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeAndDrinksBdx</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rounds/_round.html.erb
<div class="col-md-2">
  <h3 class= "text-center">Round <%= round.rank %></h3>

  <% if round.can_be_revealed? %>
    <div>Pending</div>
    <br>
    <%= link_to("Reveal", round_path(round), data: {turbo_method: :patch}, class: "btn btn-warning text-white") if current_user.admin %>
  <% elsif round.pending? %>
    <div>Pending</div>
  <% elsif round.active? %>
    <div>Active</div>
    <a href="https://www.codewars.com/kata/<%= round.exercice.url %>/train/<%= current_user.language %>" target="_blank">Lien vers l'exercice</a>
    <br>
    <%= link_to("Next", round_path(round), data: {turbo_method: :patch, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger text-white") if current_user.admin %>
  <% elsif round.pasted? %>
    <div>Pasted</div>
    <a href="https://www.codewars.com/kata/<%= round.exercice.url %>/train/<%= current_user.language %>" target="_blank">Lien vers l'exercice</a>
  <% end %>

  <% round.games.includes(:user).where(users: {role: round.role}).order(rating: :desc).each_with_index do |game, index| %>
    <div class="card win-color win-<%= index + 1 %>  w-100 p-3 my-3">
        <small class="size-18px"><%= index + 1 %> : <%= game.user.cw_nickname %></small>
        <small><i><%= game.finished_at.strftime("%H:%M:%S") %></i></small>
        <div class="d-flex w-100 justify-content-between">
          <small><%= game.user.language %></small>
          <small><%= game.rating %>pts</small>
        </div>
    </div>
  <% end %>

  <% round.unqualified_users.where(role: round.role).each do |user| %>
    <div class="card w-100 p-3 my-3">
      <small class="size-18px"><%= user.cw_nickname %></small>
      <small><i>Pending</i></small>
      <small><%= user.language %></small>
    </div>
  <% end %>
</div>

app/views/rounds/show.html.erb
<div class="container">
    <h1>Round <%= @round.rank %></h1>

    <iframe src="https://www.codewars.com/kata/57a0556c7cb1f31ab3000ad7/train/sql" frameborder="0"></iframe>
</div>  

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon border-bottom mb-5">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>